variables:
  JAVA_OPTS: "-Xms128m -Xmx256m"

snapshot:
  script:
    - gradle :app-snapshot:assembleDebug
  artifacts:
    paths:
      - app-snapshot/build/outputs/apk/
  except:
    - /^v.*$/

release:
  script:
    - cp /opt/private/signing.properties ./
    - gradle :app:assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/
  tags:
    - release
  only:
    - /^v.*$/
