language: android
sudo: false
branches:
  only:
    - master
env:
    - secure: "oxO/WejcfoGBUlQArNtIG6Sk7SJvbtcYr4G3EEELZaKZkbfrEKqjPBvrrVXy/Aik8nGL9AbmbZNKjGk2IJnLIr2Axd2wYr3ME6dnwBtOC6IUi10fAF3B7WnD5Vmbs5VHsH5UfoaswEKnH6LwMkzn/UDOKtLqeGVut0JX0ZoyB8s="

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
    -  $HOME/PaperAirplane-Dev-Team/BlackLight/app-snapshot/build/
    -  $HOME/PaperAirplane-Dev-Team/BlackLight/blacklight-base/build/
    -  $HOME/PaperAirplane-Dev-Team/BlackLight/.gradle/
    -  $HOME/.gradle/caches/
    -  $HOME/.gradle/wrapper/

script:
    - gradle :app-snapshot:assembleDebug :app-snapshot:assembleDebugMinify :app-snapshot:lintDebug

after_success:
- git config --global user.email "harry-chen@outlook.com"
- git config --global user.name "PAPDT Robot"
- export GIT_TAG=snapshot-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")_${TRAVIS_BUILD_NUMBER}_$(git log --format="%h" -n 1)
- git tag $GIT_TAG
- git push --quiet https://$GITHUBKEY@github.com/PaperAirplane-Dev-Team/BlackLight.git $GIT_TAG
- cd app-snapshot/build/outputs/
- tar cvf lint-results.tar lint-results-debug.html lint-results-debug.xml lint-results-debug_files
- cd ../../../

android:
  components:
  - build-tools-21.1.2
  - android-23
  - extra-android-support
  - extra-android-m2repository

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: "bBFMDthm2NQuUCXfSRw8EvkyN7seHGxD8BvsvqudSuPpmSTNRcA1JJuANeH7WVMwJjKkySVCf+SjMbHeGzahRRo7COsQ4D70q8ctad9lo1bLwt2UvgFB+c1ux6jzixsGTcCTfmKGYKDmU+iOZ7ES4t45iPsO0VUQYO8hT2fVN+0="
  file:
  - app-snapshot/build/outputs/apk/app-snapshot-debug.apk
  - app-snapshot/build/outputs/apk/app-snapshot-debugMinify.apk
  - app-snapshot/build/outputs/lint-results.tar
  skip_cleanup: true
  on:
    repo: PaperAirplane-Dev-Team/BlackLight
